package arrays;

/**
 * Created by Ranjit Soni on 09-02-2025.
 * Author: ranjitsoni2009@gmail.com
 * <p>
 * Approach :- Contribution Technique
 * Problem Statement - Print the sum of all subArray for the given array.

 * <p>
 * Note:- PrintSubArraySumSolution3 is Optimized approach in terms of Time and Space Complexity both
 *      but Carry Forward Technique still has Time complexity O(N^2) but need to solve this problem in O(N) Time Complexity.
 */
public class PrintSubArraySumSolution4 {
    /**
     * Example :- let's say there is array [1,2,3], where index would be from 0 to arrayLength-1.
     * so possible subArray and their sum would be [0,0] and 1, [0,1] and 3, [0,2] and , [1,1], [1,2], [2,2]
     *   _________________________
     *  | subArray | Sum         |
     *   -------------------------
     *  | [0,0]    | A[0]        |
     *  | [0,1]    | A[0] + A[1] |
     *  | [0,2]    | A[0] + A[1] |
     *  | [1,1]    | A[1]        |
     *  | [1,2]    | A[1] + A[2] |
     *  | [2,2]    | A[2]        |
     *   -------------------------
     * Observation :- from above observation, we have found that if we can know the involvement of each element in sum of all sub array calculation
     * it would be quick.
     * So Bag Problem has solution to find the frequency of each element.
     * <p>
     *     Logic Explanation:
     *      1. Calculate the frequency of each element in the array by using formula generated by Bag Problem.
     *      2. Iterate over the array and calculate the sum of all subArray for each element.
     *      3. Return the sum of all subArray for the given array.
     *     Time Complexity:
     *      The time complexity is O(N) where N is the length of the array.
     *      Let's say N is the length of the array.
     *      The getSubArraySum method will take O(N) time.
     *      So, the time complexity is O(N).
     *      As per Big Oh rules, remove lower terms and Constant coefficient
     *      then Time Complexity :: O(N)
     *     Space Complexity:
     *      The space complexity is O(1) where N is the length of the array.
     * @param array The array for which subArray sum needs to be calculated.
     * @return The sum of all subArray for the given array.
     */
    long getSubArraySum(int[] array) {
        int n = array.length;
        long sum = 0;
        for (int i = 0; i < n; i++) {
            long frequency = (long)(i+1)*(n-i);
            sum += array[i] * frequency;
        }
        return sum;
    }
}
